name: Build and deploy fb function
'on':
  push:
    branches: main
  release:
    types: [published]
jobs:
  dev-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup node 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci --ignore-scripts
        
      # Build website and move index from dist to functions
      # (This is important) You need to move, not copy, otherwise rewrite in firebase.json will not work
      - name: Build
        run: npm run build && mv dist/index.html functions/index.html
          
      # To deploy a function without a token, we need to log in to gcp by credentials
      - name: GCP auth by service account
        uses: 'google-github-actions/auth@v0'
        with:
         credentials_json: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'

      - name: Deploy cloud function
        uses: 'google-github-actions/deploy-cloud-functions@v0'
        with:
         name: # Function name here
         project_id: # Project id here
         runtime: 'nodejs16'
         description: 'Basic auth function'
         source_dir: 'functions'
         env_vars: 'USERNAME=${{ secrets.BASIC_AUTH_USERNAME }},PASSWORD=${{ secrets.BASIC_AUTH_PASS }}'
         ingress_settings: 'ALLOW_ALL' #Allow all requests
         entry_point: 'basicAuth'
      
      - name: Push website
        uses: FirebaseExtended/action-hosting-deploy@v0
     
